const portfolio = [
  {
    id: 1,
    category: "Grua SL",
    name: "Grua SL",
    tag: "Grua SL são equipamentos de alta performance, projetados para atender aos mais altos padrões de qualidade e segurança.",
    image: "/images/Grua-SL/Grua-SL-1.webp",
    projectInfo: {
      date: "23 de julho de 2020",
      clientName: "Marinha Do Brasil",
      projectType: "Grua",
    },
    listImages: [
      { src: "/images/Grua-SL/Grua-SL-1.webp", alt: "Grua-SL-1" },
      { src: "/images/Grua-SL/Grua-SL-2.webp", alt: "Grua-SL-2" },
      { src: "/images/Grua-SL/Grua-SL-3.webp", alt: "Grua-SL-3" },
      { src: "/images/Grua-SL/Grua-SL-4.webp", alt: "Grua-SL-4" },
      { src: "/images/Grua-SL/Grua-SL-5.webp", alt: "Grua-SL-5" },
      { src: "/images/Grua-SL/Grua-SL-6.webp", alt: "Grua-SL-6" },
      { src: "/images/Grua-SL/Grua-SL-7.webp", alt: "Grua-SL-7" },
      { src: "/images/Grua-SL/Grua-SL-8.webp", alt: "Grua-SL-8" },
      { src: "/images/Grua-SL/Grua-SL-9.webp", alt: "Grua-SL-9" },
      { src: "/images/Grua-SL/Grua-SL-10.webp", alt: "Grua-SL-10" },
      { src: "/images/Grua-SL/Grua-SL-11.webp", alt: "Grua-SL-11" },
      { src: "/images/Grua-SL/Grua-SL-12.webp", alt: "Grua-SL-12" },
      { src: "/images/Grua-SL/Grua-SL-13.webp", alt: "Grua-SL-13" },
      { src: "/images/Grua-SL/Grua-SL-14.webp", alt: "Grua-SL-14" },
    ],
  },
  {
    id: 2,
    category: "Projeto Especial",
    name: "Projeto Especial",
    tag: "Desenvolvimento de equipamento especial para realização da troca de 872 telhas de 24m e 9 toneladas cada.",
    image: "/images/Projetos-Especiais/Projetos-2.webp",
    projectInfo: {
      date: "23 de julho de 2020",
      clientName: "CBA Alumínio",
      projectType: "Projeto Especial",
    },
    listImages: [
      { src: "/images/Projetos-Especiais/Projetos-2.webp", alt: "Projetos-2" },
      { src: "/images/Projetos-Especiais/Projetos-1.webp", alt: "Projetos-1" },
      { src: "/images/Projetos-Especiais/Projetos-3.webp", alt: "Projetos-3" },
      { src: "/images/Projetos-Especiais/Projetos-4.webp", alt: "Projetos-4" },
      { src: "/images/Projetos-Especiais/Projetos-5.webp", alt: "Projetos-5" },
      { src: "/images/Projetos-Especiais/Projetos-6.webp", alt: "Projetos-6" },
      { src: "/images/Projetos-Especiais/Projetos-7.webp", alt: "Projetos-7" },
      { src: "/images/Projetos-Especiais/Projetos-8.webp", alt: "Projetos-8" },
      { src: "/images/Projetos-Especiais/Projetos-9.webp", alt: "Projetos-9" },
      { src: "/images/Projetos-Especiais/Projetos-10.webp", alt: "Projetos-10" },
      { src: "/images/Projetos-Especiais/Projetos-11.webp", alt: "Projetos-11" },
      { src: "/images/Projetos-Especiais/Projetos-12.webp", alt: "Projetos-12" },
      { src: "/images/Projetos-Especiais/Projetos-13.webp", alt: "Projetos-13" },
      { src: "/images/Projetos-Especiais/Projetos-14.webp", alt: "Projetos-14" },
      { src: "/images/Projetos-Especiais/Projetos-15.webp", alt: "Projetos-15" },
      { src: "/images/Projetos-Especiais/Projetos-16.webp", alt: "Projetos-16" },
      { src: "/images/Projetos-Especiais/Projetos-17.webp", alt: "Projetos-17" },
      { src: "/images/Projetos-Especiais/Projetos-18.webp", alt: "Projetos-18" },
      { src: "/images/Projetos-Especiais/Projetos-19.webp", alt: "Projetos-19" },
    ],
  },
  {
    id: 3,
    category: "Grua Potain",
    name: "Grua Potain",
    tag: "Fornecimento de Grua Potain para a construção de uma chaminé de reator nuclear.",
    image: "/images/Grua-Potain/Grua-Potain-1.webp",
    projectInfo: {
      date: "23 de julho de 2020",
      clientName: "Grua Potain",
      projectType: "Grua Potain",
    },
    listImages: [
      { src: "/images/Grua-Potain/Grua-Potain-1.webp", alt: "Grua-Potain-1" },
      { src: "/images/Grua-Potain/Grua-Potain-2.webp", alt: "Grua-Potain-2" },
      { src: "/images/Grua-Potain/Grua-Potain-3.webp", alt: "Grua-Potain-3" },
      { src: "/images/Grua-Potain/Grua-Potain-4.webp", alt: "Grua-Potain-4" },
      { src: "/images/Grua-Potain/Grua-Potain-5.webp", alt: "Grua-Potain-5" },
      { src: "/images/Grua-Potain/Grua-Potain-6.webp", alt: "Grua-Potain-6" },
      { src: "/images/Grua-Potain/Grua-Potain-7.webp", alt: "Grua-Potain-7" },
      { src: "/images/Grua-Potain/Grua-Potain-8.webp", alt: "Grua-Potain-8" },
      { src: "/images/Grua-Potain/Grua-Potain-9.webp", alt: "Grua-Potain-9" },
      { src: "/images/Grua-Potain/Grua-Potain-10.webp", alt: "Grua-Potain-10" },
      { src: "/images/Grua-Potain/Grua-Potain-11.webp", alt: "Grua-Potain-11" },
      { src: "/images/Grua-Potain/Grua-Potain-12.webp", alt: "Grua-Potain-12" },
      { src: "/images/Grua-Potain/Grua-Potain-13.webp", alt: "Grua-Potain-13" },
      { src: "/images/Grua-Potain/Grua-Potain-14.webp", alt: "Grua-Potain-14" },
      { src: "/images/Grua-Potain/Grua-Potain-15.webp", alt: "Grua-Potain-15" },
      { src: "/images/Grua-Potain/Grua-Potain-16.webp", alt: "Grua-Potain-16" },
    ],
  },
  {
    id: 4,
    category: "Nossa Fábrica",
    name: "Nossa Fábrica",
    tag: "Nossa fábrica é um espaço onde produzimos equipamentos de alta qualidade para atender às necessidades de nossos clientes.",
    image: "/images/fabrica/Fabrica-1.webp",
    projectInfo: {
      date: "23 de julho de 2020",
      clientName: "Nossa Fábrica",
      projectType: "Nossa Fábrica",
    },
    listImages: [
      { src: "/images/fabrica/Fabrica-1.webp", alt: "Fabrica-1" },
      { src: "/images/fabrica/Fabrica-2.webp", alt: "Fabrica-2" },
      { src: "/images/fabrica/Fabrica-3.webp", alt: "Fabrica-3" },
      { src: "/images/fabrica/Fabrica-4.webp", alt: "Fabrica-4" },
      { src: "/images/fabrica/Fabrica-5.webp", alt: "Fabrica-5" },
      { src: "/images/fabrica/Fabrica-6.webp", alt: "Fabrica-6" },
      { src: "/images/fabrica/Fabrica-7.webp", alt: "Fabrica-7" },
      { src: "/images/fabrica/Fabrica-8.webp", alt: "Fabrica-8" },
      { src: "/images/fabrica/Fabrica-9.webp", alt: "Fabrica-9" },
      { src: "/images/fabrica/Fabrica-10.webp", alt: "Fabrica-10" },
    ],
  },
];

export default portfolio;
